### PR TITLE
Update format/doc-type logic after format retirement

### PR DESCRIPTION
**Pull request by timblair**
The `format` field as a response from the content store has been [retired][] and replaced with a combination of `schema_name` and `document_type`.

This is not the cleanest solution: we're now exposing the document type as `format` in the API response, which doesn't match up exactly with the old values, and is now mis-named. However, the only app which currently uses this API is info-frontend, and that doesn't use the `format` value.

In addition, we should be changing info-frontend to talk to the Performance Platform directly, rather than through metadata-api, which means we can retire metadata-api entirely.

[retired]: https://github.com/alphagov/govuk-rfcs/blob/fec5141c/rfc-041-separate-document-type-from-format.md

Feedback appreciated, especially around the format / doc type / schema name logic change.

/cc @tijmenb @chao-xian @gpeng

### CODE REVIEW

**Comment by tijmenb** [comment]
The logic looks good. 

> This is not the cleanest solution: we're now exposing the document type as format in the API response, which doesn't match up exactly with the old values, and is now mis-named. However, the only app which currently uses this API is info-frontend, and that doesn't use the format value.

If info-frontend doesn't use the format value can we remove it from here?

**Comment by timblair** [comment]
We can: I was being over-cautious _just in case_ something, somewhere, still relies on it. Given that we're likely to be binning the whole thing soon, I didn't think it were worth the investigative effort.

**Comment by tijmenb** [comment]
Fair enough!

**Review by tijmenb — APPROVED** [review]

**Comment by chao-xian** [comment]
I can confirm that this works for me locally:

## Before
image


## After
image

**Pull request merged**
