### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by steventux**
https://trello.com/c/TpBi03x6/568-move-apps-to-new-ci-infrastructure-1

Do not merge - some issues with the deployment config getting the artefact from Jenkins 2.

### CODE REVIEW

**Comment by steventux** [comment]
@gpeng the deploy job should work as it's on a downstream (old) Jenkins.

**Comment by gpeng** [comment]
Sorry... I didn't mean the job itself. It's still looking for the build artefact on old CI here https://github.com/alphagov/govuk-app-deployment/blob/master/metadata-api/config/deploy.rb#L22

**Comment by steventux** [comment]
Ah thanks @gpeng I didn't know about this, will update.

**Comment by steventux** [comment]
@gpeng see https://ci.integration.publishing.service.gov.uk/job/metadata-api/job/add-jenkinsfile/27/console for running tests.

**Pull request merged**
